name: Send shanbay today new words to telegram

on:
  workflow_dispatch:
  schedule:
    - cron: "*/30 * * * *"
  push:
    branches:
      - master
    paths:
      - shanbay.js
env:
  TZ: Asia/Shanghai

jobs:
  sender:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: FedericoCarboni/setup-ffmpeg@v1-beta
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: Run Script
        run: |
          node shanbay.js ${{ secrets.TELE_TOKEN }} ${{ secrets.TELE_CHAT_ID }} "${{ secrets.SHANBAY_COOKIE }}"
      - name: use ffmpeg combine and send
        id: setup-ffmpeg
        run: | 
          (ls "$(pwd)"/MP3_NEW/*.mp3 >> /dev/null 2>&1) || ffmpeg -y -f concat -safe 0 -i <(find "$(pwd)"/MP3_NEW -iname "*.mp3" -printf "file "%p"\n" | sort) -c copy "$(pwd)"/$(date +"%m%d")_new_words.mp3
          (ls "$(pwd)"/MP3_REVIEW/*.mp3 >> /dev/null 2>&1) || ffmpeg -y -f concat -safe 0 -i <(find "$(pwd)"/MP3_REVIEW -iname "*.mp3" -printf "file "%p"\n" | sort) -c copy "$(pwd)"/$(date +"%m%d")_review_words.mp3
          (ls $(date +"%m%d")_new_words.mp3 >> /dev/null 2>&1) || curl -v "chat_id=${{ secrets.TELE_CHAT_ID }}" --form-string  document=@$(date +"%m%d")_new_words.mp3 https://api.telegram.org/bot${{ secrets.TELE_TOKEN }}/sendDocument
          (ls $(date +"%m%d")_review_words.mp3 >> /dev/null 2>&1) || curl -v "chat_id=${{ secrets.TELE_CHAT_ID }}" --form-string  document=@$(date +"%m%d")_review_words.mp3 https://api.telegram.org/bot${{ secrets.TELE_TOKEN }}/sendDocument
